In [3]:
import numpy as np

In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [26]:
def identity_function(x):
    return x

In [27]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c) # 오버플로 때문에 처리
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [7]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

A1 = np.dot(X, W1) + B1
A1

array([0.3, 0.7, 1.1])

In [9]:
Z1 = sigmoid(A1)
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [13]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

A2 = np.dot(Z1, W2) + B2
A2

array([0.51615984, 1.21402696])

In [14]:
Z2 = sigmoid(A2)
Z2

array([0.62624937, 0.7710107 ])

In [16]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)
Y

array([0.31682708, 0.69627909])

In [19]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])

    return network

def forword(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)

    return y

network = init_network()
x = np.array([1.0, 0.5])
y = forword(network, x)
print(y)


[0.31682708 0.69627909]


# 소프트맥스 함수

In [22]:
a = np.array([0.3, 2.9, 4.0])

exp_a = np.exp(a)
exp_a

array([ 1.34985881, 18.17414537, 54.59815003])

In [24]:
sum_exp_a = np.sum(exp_a)
sum_exp_a

np.float64(74.1221542101633)

In [28]:
y = exp_a / sum_exp_a
y

array([0.01821127, 0.24519181, 0.73659691])

### 소프트맥스 함수 오버플로우

In [30]:
# 제대로 계산되지 않는다.
a = np.array([1010, 1000, 990])
np.exp(a) / np.sum(np.exp(a))

C:\Users\msl92\AppData\Local\Temp\ipykernel_34104\1653604333.py:3: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))
C:\Users\msl92\AppData\Local\Temp\ipykernel_34104\1653604333.py:3: RuntimeWarning: invalid value encountered in divide
  np.exp(a) / np.sum(np.exp(a))


array([nan, nan, nan])

In [33]:
c = np.max(a)
a - c
np.exp(a - c) / np.sum(np.exp(a - c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [35]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)

y

array([0.01821127, 0.24519181, 0.73659691])

In [37]:
np.sum(y) # 소프트맥스 결과의 합은 1이 된다

np.float64(1.0)

In [61]:
import sys, os
import pickle
import gzip
# sys.path.append(os.pardir)
from mnist import load_mnist

In [62]:
# (x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)

def _load_img(file_name):
    file_path = dataset_dir + "/" + file_name
    
    print("Converting " + file_name + " to NumPy Array ...")    
    with gzip.open(file_path, 'rb') as f:
            data = np.frombuffer(f.read(), np.uint8, offset=16)
    data = data.reshape(-1, img_size)
    print("Done")
    
    return data


project_root = os.path.abspath('../..')

file1 = 't10k-images-idx3-ubyte.gz'
file2 = 't10k-labels-idx1-ubyte.gz'
file3 = 'train-images-idx3-ubyte.gz'
file4 = 'train-labels-idx1-ubyte.gz'

img_size = 784

with open(project_root + '/dataset/mnist/' + file1, 'rb') as f:

    with gzip.open(f, 'rb') as g:
        data = np.frombuffer(g.read(), np.uint8, offset=16)

    data = data.reshape(-1, img_size)

    dataset = pickle.load(data)
    print(dataset)


TypeError: file must have 'read' and 'readline' attributes